---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: CEEMS API Server
    description:
      - Deploy L(CEEMS API server,https://github.com/ceems-dev/ceems_api_server) using ansible
    author:
      - Mahendra Paipuri
    options:
      ceems_api_server_version:
        description: CEEMS API server package version. Also accepts latest as parameter.
        default: "0.9.1"
      ceems_api_server_skip_install:
        description: CEEMS API server installation tasks gets skipped when set to true.
        type: bool
        default: false
      ceems_api_server_binary_local_dir:
        description:
          - Enables the use of local packages instead of those distributed on github.
          - The parameter may be set to a directory where the C(ceems_api_server) binary is stored on the host where ansible is run.
          - This overrides the I(ceems_api_server_version) parameter
      ceems_api_server_binary_url:
        description: URL of the ceems API server binaries .tar.gz file
        default: https://github.com/{{ _ceems_api_server_repo }}/releases/download/v{{ ceems_api_server_version }}/ceems-{{ ceems_api_server_version }}.linux-{{ go_arch }}.tar.gz
      ceems_api_server_checksums_url:
        description: URL of the ceems API server checksums file
        default: https://github.com/{{ _ceems_api_server_repo }}/releases/download/v{{ ceems_api_server_version }}/sha256sums.txt
      ceems_api_server_web_listen_address:
        description: Address on which ceems API server will listen
        default: "0.0.0.0:9020"
      ceems_api_server_config:
        description:
          - CEEMS API server config. Configuration under key L(`ceems_api_server` docs,https://ceems-dev.github.io/ceems/docs/configuration/ceems-api-server)
          - These files include the SQLite database.
        type: dict
        required: true
      ceems_api_server_clusters_config:
        description:
          - List of clusters that are monitored by CEEMS.
          - Each element in list be of L(`cluster_config`,https://ceems-dev.github.io/ceems/docs/configuration/ceems-api-server#cluster_config)
        type: list
        elements: dict
      ceems_api_server_updaters_config:
        description:
          - List of updaters used by CEEMS.
          - Each element in list be of L(`updater_config`,https://ceems-dev.github.io/ceems/docs/configuration/ceems-api-server#updater_config)
        type: list
        elements: dict
      ceems_api_server_tls_server_config:
        description:
          - Configuration for TLS authentication.
          - Keys and values are the same as in L(ceems_api_server docs,https://prometheus.io/docs/prometheus/latest/configuration/https/).
        type: dict
      ceems_api_server_http_server_config:
        description:
          - Config for HTTP/2 support.
          - Keys and values are the same as in L(ceems_api_server docs,https://prometheus.io/docs/prometheus/latest/configuration/https/).
        type: dict
      ceems_api_server_basic_auth_users:
        description: Dictionary of users and password for basic authentication. Passwords are automatically hashed with bcrypt.
        type: dict
      ceems_api_server_binary_install_dir:
        description:
          - I(Advanced)
          - Directory to install CEEMS API server binary
        default: /usr/local/bin
      ceems_api_server_create_system_user_group:
        description:
          - I(Advanced)
          - Create system user and group for CEEMS API server
        default: true
      ceems_api_server_system_group:
        description:
          - I(Advanced)
          - System group for CEEMS API server server
        default: ceems
      ceems_api_server_system_user:
        description:
          - I(Advanced)
          - CEEMS API server user
        default: ceems
      ceems_api_server_cli_args:
        description:
          - I(Advanced)
          - Additional CLI arguments that will be passed to CEEMS API server
        type: list
        elements: str
      ceems_api_server_env_vars:
        description:
          - I(Advanced)
          - Environment variables will be passed to CEEMS API server
        type: dict
